name:                ex3codeSol
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ex3codeSol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ex3codeSol

tests:
  ex3codeSol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ex3codeSol
    - hspec >= 2.5.4 && < 3
    - QuickCheck >= 2.11.3 && < 3
