name:                ex0codeSol
version:             0.1.0.0
github:              "githubuser/ex0codeSol"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ex0codeSol#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  ex0codeSol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ex0codeSol
    - hspec >= 2.5.4 && < 3
    - QuickCheck >= 2.11.3 && < 3
